{
 "title": "Pinpoint Events",
 "time": { "from": "2021-01-27T20:01:00.697Z", "to": "2021-01-27T20:03:05.230Z" },
 "templating": {
  "list": [
   { "name": "SMS_COUNTRY_CODE", "label": "SMS Country Code", "query": "US,BR,UK,JP,FR,ZA" }
  ]
 },
 "panels": [
  {
   "title": "Email Statistics",
   "type": "graph",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.delivered\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE $__timeFilter\nAND event_type = '_email.delivered'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    },
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.send\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE event_type = '_email.send'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    },
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.complaint\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE event_type = '_email.complaint'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    },
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.hardbounce\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE event_type = '_email.hardbounce'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    },
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.softbounce\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE $__timeFilter\nAND event_type = '_email.softbounce'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    }
   ]
  },
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Complaints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.complaint\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE event_type = '_email.complaint'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    }
   ]
  },
  {
   "title": "Bounces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.hardbounce\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE event_type = '_email.hardbounce'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    },
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, count(event_type) as \"_email.softbounce\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE event_type = '_email.softbounce'\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc"
    }
   ]
  },
  {
   "title": "SMS Costs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, 1s) AS time_bin, sum(measure_value::double) as \"cost\"\nFROM \"PinpointEvents\".\"PinpointEvents\"\nWHERE event_type = '_sms.buffered' AND iso_country_code IN (${SMS_COUNTRY_CODE:sqlstring})\nGROUP BY BIN(time, 1s)\nORDER BY time_bin asc\n"
    }
   ]
  }
 ]
}